name: notable_moments
description: A new Flutter project.
publish_to: "none"
version: 1.0.67

environment:
  sdk: ">=3.6.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  flutter_riverpod: ^2.6.1
  responsive_framework: ^1.5.1
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  image_picker: ^1.0.8
  flutter_dotenv: ^5.2.1
  yandex_maps_mapkit: ^4.16.0-beta
  either_dart: ^1.0.0
  intl: ^0.20.2
  collection: ^1.19.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.2
  share_plus: ^11.0.0
  cached_network_image: ^3.4.1
  syncfusion_flutter_pdfviewer: ^29.2.10
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2   # ✅ Добавлено для локального хранения флагов (онбординг и др.)
  flutter_easylogger: ^2.3.3 #https://pub.dev/packages/flutter_easylogger
  timeline_tile_plus: ^0.0.3 #https://pub.dev/packages/timeline_tile_plus
  gap: ^3.0.1 #https://pub.dev/packages/gap

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/svg/
    - assets/icon/
    - assets/placemark/
    - assets/pdf/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
